apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  name: tekton-simple-django-app-1
  generateName: tekton-kn-sample-
spec:
  pipelineRef:
    name: build-and-deploy-pipeline
  serviceAccountName: pipeline-account
  resources:
    - name: git-source
      resourceRef:
        name: tekton-knative-git
  params:
    - name: pathToContext
      value: ""
    - name: pathToDockerFile
      value: "Dockerfile"
    - name: pathToYamlFile
      value: "knative.yaml"
    - name: imageUrl
      value: "docker.io/vtemian/simple-django-app"
    - name: imageTag
      value: "1.0"
