apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: tekton-knative-git
spec:
  type: git
  params:
    - name: revision
      value: knative
    - name: url
      value: https://github.com/vtemian/simple-django-app
